import { useEffect, useState } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useAuth } from "../auth/AuthContext";
import { canEditInterventions } from "../auth/ProtectedRoute";
import { createIntervention, interventionAssignees, listInterventions } from "../services/interventionsApi";
import { listEnvironments, listObjects, listProjects } from "../services/projectsApi";
import type { Intervention, InterventionCreate, InterventionStatus } from "../types/interventions";

const empty:InterventionCreate={client_request_id:"",project_id:"",environment_id:"",mra_object_id:"",title:"",description:"",priority:"normal",assigned_user_id:null,due_at:null};
export function InterventionsPage(){
 const {user}=useAuth(); const navigate=useNavigate(); const location=useLocation(); const queryClient=useQueryClient(); const canEdit=canEditInterventions(user?.role); const [filters,setFilters]=useState<{search?:string;status?:InterventionStatus;overdue?:boolean}>({}); const [items,setItems]=useState<Intervention[]>([]); const [cursor,setCursor]=useState<string|null>(null); const [form,setForm]=useState<InterventionCreate>(()=>({...empty,client_request_id:crypto.randomUUID()})); const [show,setShow]=useState(location.pathname.endsWith("/new")); const createMode=canEdit&&show;
 const page=useQuery({queryKey:["interventions",filters],queryFn:()=>listInterventions(filters)}); useEffect(()=>{if(page.data){setItems(page.data.items);setCursor(page.data.next_cursor)}},[page.data]);
 const projects=useQuery({queryKey:["projects"],queryFn:listProjects,enabled:createMode}); const environments=useQuery({queryKey:["environments",form.project_id],queryFn:()=>listEnvironments(form.project_id),enabled:createMode&&!!form.project_id}); const objects=useQuery({queryKey:["objects",form.environment_id],queryFn:()=>listObjects(form.environment_id),enabled:createMode&&!!form.environment_id});
 const assignees=useQuery({queryKey:["intervention-assignees"],queryFn:interventionAssignees,enabled:createMode});
 const create=useMutation({mutationFn:createIntervention,onSuccess:async(item)=>{await Promise.all([queryClient.invalidateQueries({queryKey:["interventions"]}),queryClient.invalidateQueries({queryKey:["interventions-summary"]})]);navigate(`/interventions/${item.id}`)}});
 const loadMore=async()=>{if(cursor){const next=await listInterventions(filters,cursor);setItems(old=>[...old,...next.items]);setCursor(next.next_cursor)}};
 return <section className="page"><header className="page-header"><div><p className="eyebrow">MANUTENZIONE</p><h1>Interventi</h1><p>Ordini di lavoro e attività operative.</p></div>{canEdit&&<button onClick={()=>{setForm({...empty,client_request_id:crypto.randomUUID()});setShow(true)}}>Nuovo intervento</button>}</header>
 <div className="projects-toolbar panel"><input aria-label="Cerca" placeholder="Cerca codice o titolo" value={filters.search??""} onChange={e=>setFilters({...filters,search:e.target.value})}/><select value={filters.status??""} onChange={e=>setFilters({...filters,status:(e.target.value||undefined) as InterventionStatus|undefined})}><option value="">Tutti gli stati</option>{["open","planned","in_progress","blocked","completed","cancelled"].map(x=><option key={x}>{x}</option>)}</select><label><input type="checkbox" checked={filters.overdue??false} onChange={e=>setFilters({...filters,overdue:e.target.checked||undefined})}/> Scaduti</label></div>
 {canEdit&&createMode&&<form className="project-create-card" onSubmit={e=>{e.preventDefault();create.mutate(form)}}><h2>Nuovo intervento</h2><label>Progetto<select required value={form.project_id} onChange={e=>setForm({...form,project_id:e.target.value,environment_id:"",mra_object_id:""})}><option value="">Seleziona</option>{projects.data?.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Ambiente<select required value={form.environment_id} onChange={e=>setForm({...form,environment_id:e.target.value,mra_object_id:""})}><option value="">Seleziona</option>{environments.data?.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Oggetto<select required value={form.mra_object_id} onChange={e=>setForm({...form,mra_object_id:e.target.value})}><option value="">Seleziona</option>{objects.data?.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Titolo<input required maxLength={255} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Descrizione<textarea maxLength={10000} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Priorità<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value as InterventionCreate["priority"]})}>{["low","normal","high","urgent"].map(x=><option key={x}>{x}</option>)}</select></label><label>Assegnatario<select value={form.assigned_user_id??""} onChange={e=>setForm({...form,assigned_user_id:e.target.value||null})}><option value="">Non assegnato</option>{assignees.data?.map(x=><option key={x.id} value={x.id}>{x.display_name} · {x.role}</option>)}</select></label><label>Scadenza<input type="datetime-local" onChange={e=>setForm({...form,due_at:e.target.value?new Date(e.target.value).toISOString():null})}/></label>{assignees.isError&&<p role="alert">Assegnatari non disponibili.</p>}{create.isError&&<p role="alert">{create.error.message}</p>}<button disabled={create.isPending}>Crea</button><button type="button" onClick={()=>{setShow(false);if(location.pathname.endsWith("/new"))navigate("/interventions")}}>Annulla</button></form>}
 {page.isLoading&&<p>Caricamento…</p>}{page.isError&&<p role="alert">{page.error.message}</p>}{!page.isLoading&&!page.isError&&!items.length&&<p>Nessun intervento.</p>}<div className="project-card-grid">{items.map(item=><article className="project-card" key={item.id}><div className="project-card-content"><small>{item.code}</small><h2>{item.title}</h2><p>{item.status} · {item.priority}{item.due_at?` · ${new Date(item.due_at).toLocaleDateString()}`:""}</p><Link className="button" to={`/interventions/${item.id}`}>Apri</Link></div></article>)}</div>{cursor&&<button onClick={()=>void loadMore()}>Carica altri</button>}</section>
}
