import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link, useParams } from "react-router-dom";
import { useAuth } from "../auth/AuthContext";
import { ApiError } from "../services/apiClient";
import { getIntervention, interventionAssignees, interventionKnowledge, interventionTimeline, linkInterventionKnowledge, patchIntervention, transitionIntervention, unlinkInterventionKnowledge } from "../services/interventionsApi";
import { listKnowledgeCards } from "../services/knowledgeApi";
import type { InterventionStatus } from "../types/interventions";

const choices:Record<InterventionStatus,InterventionStatus[]>={open:["planned","in_progress","cancelled"],planned:["open","in_progress","blocked","cancelled"],in_progress:["blocked","completed","cancelled"],blocked:["planned","in_progress","cancelled"],completed:["in_progress"],cancelled:[]};
export function InterventionDetailPage(){const {interventionId=""}=useParams();const {user}=useAuth();const client=useQueryClient();const item=useQuery({queryKey:["intervention",interventionId],queryFn:()=>getIntervention(interventionId)});const timeline=useQuery({queryKey:["intervention-timeline",interventionId],queryFn:()=>interventionTimeline(interventionId)});const links=useQuery({queryKey:["intervention-knowledge",interventionId],queryFn:()=>interventionKnowledge(interventionId)});const [target,setTarget]=useState<InterventionStatus|"">("");const [note,setNote]=useState("");const [resolution,setResolution]=useState("");
 const cards=useQuery({queryKey:["knowledge-cards","intervention-link"],queryFn:()=>listKnowledgeCards(),enabled:user?.role!=="viewer"});const assignees=useQuery({queryKey:["intervention-assignees"],queryFn:interventionAssignees,enabled:user?.role!=="viewer"});const [cardId,setCardId]=useState("");const [title,setTitle]=useState("");const [description,setDescription]=useState<string|undefined>(undefined);const [priority,setPriority]=useState<""|"low"|"normal"|"high"|"urgent">("");const [assignee,setAssignee]=useState<string|undefined>(undefined);const [dueAt,setDueAt]=useState<string|undefined>(undefined);
 const refresh=()=>Promise.all([client.invalidateQueries({queryKey:["intervention",interventionId]}),client.invalidateQueries({queryKey:["intervention-timeline",interventionId]}),client.invalidateQueries({queryKey:["intervention-knowledge",interventionId]}),client.invalidateQueries({queryKey:["interventions"]}),client.invalidateQueries({queryKey:["interventions-summary"]})]);
 const edit=useMutation({mutationFn:()=>patchIntervention(interventionId,{expected_version:item.data!.version,...(title?{title}:{}),...(description!==undefined?{description}:{}),...(priority?{priority}:{}),...(assignee!==undefined?{assigned_user_id:assignee||null}:{}),...(dueAt!==undefined?{due_at:dueAt?new Date(dueAt).toISOString():null}:{})}),onSuccess:refresh,onError:async(error)=>{if(error instanceof ApiError&&error.status===409)await refresh()}});
 const link=useMutation({mutationFn:()=>linkInterventionKnowledge(interventionId,{knowledge_card_id:cardId,usage_type:"diagnostic_reference",note:""}),onSuccess:refresh});const unlink=useMutation({mutationFn:(linkId:string)=>unlinkInterventionKnowledge(interventionId,linkId),onSuccess:refresh});
 const transition=useMutation({mutationFn:()=>transitionIntervention(interventionId,{command_id:crypto.randomUUID(),expected_version:item.data!.version,to_status:target as InterventionStatus,note:note||undefined,resolution_summary:resolution||undefined}),onSuccess:async()=>{await refresh();setTarget("");setNote("");setResolution("")},onError:async(error)=>{if(error instanceof ApiError&&error.status===409)await refresh()}});
 if(item.isLoading)return <p>Caricamento…</p>;if(item.isError||!item.data)return <p role="alert">Intervento non disponibile.</p>;const allowed=choices[item.data.status].filter(x=>(x!=="cancelled"&&item.data.status!=="completed")||user?.role==="admin");return <section className="page"><Link to="/interventions">← Interventi</Link><header className="page-header"><div><p className="eyebrow">{item.data.code}</p><h1>{item.data.title}</h1><p>{item.data.status} · priorità {item.data.priority} · versione {item.data.version}</p></div></header><section className="panel"><h2>Dettagli</h2><p>{item.data.description||"Nessuna descrizione."}</p><p>Progetto {item.data.project_id}<br/>Ambiente {item.data.environment_id}<br/>Oggetto {item.data.mra_object_id}</p>{item.data.resolution_summary&&<p><strong>Risoluzione:</strong> {item.data.resolution_summary}</p>}</section>
 {user?.role!=="viewer"&&!(["completed","cancelled"] as InterventionStatus[]).includes(item.data.status)&&<form className="panel" onSubmit={e=>{e.preventDefault();edit.mutate()}}><h2>Modifica</h2><input aria-label="Titolo" placeholder={item.data.title} value={title} onChange={e=>setTitle(e.target.value)}/><textarea aria-label="Descrizione" placeholder={item.data.description||"Descrizione"} value={description??""} onChange={e=>setDescription(e.target.value)}/><select aria-label="Priorità" value={priority} onChange={e=>setPriority(e.target.value as typeof priority)}><option value="">{item.data.priority}</option>{["low","normal","high","urgent"].map(value=><option key={value}>{value}</option>)}</select><select aria-label="Assegnatario" value={assignee??item.data.assigned_user_id??""} onChange={e=>setAssignee(e.target.value)}><option value="">Non assegnato</option>{assignees.data?.map(value=><option key={value.id} value={value.id}>{value.display_name} · {value.role}</option>)}</select><input aria-label="Scadenza" type="datetime-local" value={dueAt??""} onChange={e=>setDueAt(e.target.value)}/><button disabled={edit.isPending||(!title&&description===undefined&&!priority&&assignee===undefined&&dueAt===undefined)}>Salva</button>{edit.isError&&<p role="alert">{edit.error instanceof ApiError&&edit.error.status===409?"Dato aggiornato da un altro utente":edit.error.message}</p>}</form>}
 {user?.role!=="viewer"&&allowed.length>0&&<form className="panel" onSubmit={e=>{e.preventDefault();transition.mutate()}}><h2>Cambia stato</h2><select required value={target} onChange={e=>setTarget(e.target.value as InterventionStatus)}><option value="">Seleziona</option>{allowed.map(x=><option key={x}>{x}</option>)}</select><textarea maxLength={1000} placeholder="Nota" value={note} onChange={e=>setNote(e.target.value)}/>{target==="completed"&&<textarea maxLength={5000} placeholder="Risoluzione" value={resolution} onChange={e=>setResolution(e.target.value)}/>}<button disabled={transition.isPending}>Conferma</button>{transition.isError&&<p role="alert">{transition.error instanceof ApiError&&transition.error.status===409?"Dato aggiornato da un altro utente":transition.error.message}</p>}</form>}
 <section className="panel"><h2>Timeline</h2>{timeline.isLoading&&<p>Caricamento…</p>}{timeline.isError&&<p role="alert">Timeline non disponibile.</p>}{timeline.data?.map(event=><article key={event.id}><strong>{event.event_type}</strong> · {event.actor_display_name_snapshot}<p>{event.from_status??"inizio"} → {event.to_status??"-"}{event.note?` · ${event.note}`:""}</p><small>{new Date(event.occurred_at).toLocaleString()}</small></article>)}</section><section className="panel"><h2>Knowledge collegata</h2>{links.isError&&<p role="alert">Collegamenti Knowledge non disponibili.</p>}{user?.role!=="viewer"&&!(["completed","cancelled"] as InterventionStatus[]).includes(item.data.status)&&<form onSubmit={e=>{e.preventDefault();link.mutate()}}><select required value={cardId} onChange={e=>setCardId(e.target.value)}><option value="">Seleziona scheda</option>{cards.data?.map(card=><option key={card.id} value={card.id}>{card.code} · {card.title}</option>)}</select><button disabled={link.isPending}>Collega</button>{link.isError&&<p role="alert">Collegamento non riuscito.</p>}</form>}{links.data?.length?links.data.map(value=><p key={value.id}>{value.usage_type} · {value.knowledge_card_id}{user?.role!=="viewer"&&!(["completed","cancelled"] as InterventionStatus[]).includes(item.data.status)&&<button onClick={()=>unlink.mutate(value.id)}>Scollega</button>}</p>):!links.isLoading&&!links.isError&&<p>Nessun collegamento.</p>}{unlink.isError&&<p role="alert">Scollegamento non riuscito.</p>}</section>{user?.role==="admin"&&<Link to={`/activity?entity_type=intervention&entity_id=${item.data.id}`}>Apri audit</Link>}</section>}
